### ISSUE TITLE
View slider improvements

### ISSUE THREAD

**Issue by tlylt** [Berted/coNote#64] opened 2022-07-01 15:07 UTC
Consider adding three buttons for convenient setting of the slider to min, max, and middle
![image](https://user-images.githubusercontent.com/41845017/176920798-e36fef48-c2e7-407f-8180-9ea7b27e55ed.png)

**Comment by Berted** [comment] 2022-07-19 12:09
At first, we had decided to close this issue, as we had initially planned to implement a more proper split-bar view solution (think of how VSCode markdown preview would work). However, we decided to step away from this idea and continue using the current slider on the navbar for two reasons:
- We have limited time to complete this feature. Not only that, the view slider is serviceable and entirely usable for now.
- Performance issues on rendering caused by main thread blocking as mentioned in #97. As such, implementing a smooth split view panel will not be possible due to the hitches caused by react-markdown as of current. (Note that this is also why the slider is discrete instead of smooth)

As such, we've now taken this issue into consideration. Currently implementing a solution.

**Closed as completed** 2022-07-22 05:00 UTC
Labels: enhancement
